version: '3.3'

services:
  db:
    container_name: finby
    image: postgres:14-alpine
    volumes:
      - finby_data:/var/lib/postgresql/data/
    env_file:
      - ./.env
    ports:
      - 5432:5432

volumes:
  finby_data:
    name: finby_data
